 
export const getcategoryConstant = {
    GET_ALL_CATEGORY_REQUEST:"GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS:"GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE:"GET_ALL_CATEGORY_FAILURE",
    ADD_NEW_CATEGORY_REQUEST:"ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS:"ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE:"ADD_NEW_CATEGORY_FAILURE",
    
}



export const getProductSlugConstant = {
 
    GET_PRODUCT_BYSLUG_SUCCESS:"GET_PRODUCT_BYSLUG_SUCCESS",
    GET_PRODUCT_PAGE_REQUEST:"GET_PRODUCT_PAGE_REQUEST",
    GET_PRODUCT_PAGE_SUCCESS:"GET_PRODUCT_PAGE_SUCCESS",
    GET_PRODUCT_PAGE_FAILURE:"GET_PRODUCT_PAGE_FAILURE",
}


export const authConstants = {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE",
    
}