 
export const getcategoryConstant = {
    GET_ALL_CATEGORY_REQUEST:"GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCESS:"GET_ALL_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_FAILURE:"GET_ALL_CATEGORY_FAILURE",
    ADD_NEW_CATEGORY_REQUEST:"ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS:"ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE:"ADD_NEW_CATEGORY_FAILURE",
    
}



export const getProductSlugConstant = {
    GET_PRODUCT_BYSLUG_REQUEST:"GET_PRODUCT_BYSLUG_REQUEST",
    GET_PRODUCT_BYSLUG_SUCCESS:"GET_PRODUCT_BYSLUG_SUCCESS",
    GET_PRODUCT_BYSLUG_FAILURE:"GET_PRODUCT_BYSLUG_FAILURE",
}